name: Build EXE for Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 PyQt6-Charts customtkinter
    - name: Run PyInstaller
      run: |
        cd AK_GALA_ERP_V13
        pyinstaller --onefile --windowed --name "AK_GALA" --icon=project.ico main.py

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/*.exe


